WebUI/Instagram.Analysis/Controllers/MediaController.cs
namespace Instagram.Controllers
{
    using Instagram.Analysis.Helpers;
    using Instagram.Analysis.Models;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;

    public class MediaController : Controller
    {
        // GET: Media
        public ActionResult Index(string code)
        {
            var ban = CacheHelper.BanMedias.Where(x => x.Value == code).FirstOrDefault();
            if (ban != null)
                return RedirectToAction("Index", "Home", new { q = "media-is-block" });

            if (!Request.Path.EndsWith("/"))
                return RedirectPermanent(Request.Url.ToString() + "/");

            if (string.IsNullOrEmpty(code))
                return RedirectToAction("Index", "Home", new { q = "media-code-empty" });

            var model = new MediaViewModel()
            {
                Code = code,
                IsEnableAds = false,
            };

            return View(model);
        }

        [HttpGet]
        [ValidateInput(false)]
        public ActionResult Ban(string code, int type)
        {
            if (string.IsNullOrEmpty(code))
                return RedirectToAction("Index", "Home", new { q = "code-empty" });

            var model = new Model.BanMedia()
            {
                Description = "ban",
                Value = code,
            };

            CacheHelper.BanMedias.Add(model);

            var result = new Data.BanMediaData().Insert(model);
            if (result.IsSucceed)
                return RedirectToAction("Index", "Home", new { q = "media_banned" });
            else
                return RedirectToAction("Index", "Home", new { q = "media_error_banned" });
        }
    }
}

WebUI/Instagram.Analysis/Controllers/PageController.cs
namespace Instagram.Controllers
{
    using Instagram.Data;
    using Instagram.Analysis.Models;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;

    public class PageController : Controller
    {
        public ActionResult Index(string username)
        {
            if (string.IsNullOrEmpty(username))
                username = "";

            Random rnd = new Random();
            
            var model = new ReportModel()
            {
                Fullname = "",
                MailAddress = "",
                Message = "",
                Username = username,
                Subject = "",
                Captha1 = rnd.Next(1,9),
                Captha2 = rnd.Next(1,9),
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult Index(string fullname, string mail, string message, string username, string subject, int capt1, int capt2, int captcha)
        {
            int capResult = capt1 + capt2;
            var errorList = new List<string>();
            if (captcha <= 0)
                errorList.Add("Captcha empty");
            if (captcha != capResult)
                errorList.Add("Captcha Error");
            if(string.IsNullOrEmpty(fullname))
                errorList.Add("Fullname empty");
            if (string.IsNullOrEmpty(mail))
                errorList.Add("EMail empty");
            if (string.IsNullOrEmpty(message))
                errorList.Add("Message empty");
            if (string.IsNullOrEmpty(username))
                errorList.Add("Username empty");
            if (string.IsNullOrEmpty(subject))
                errorList.Add("Subject empty");

            Random rnd = new Random();

            var model = new ReportModel()
            {
                Fullname = fullname,
                MailAddress = mail,
                Message = message,
                Subject = subject,
                Username = username,
                Captha1 = rnd.Next(1, 9),
                Captha2 = rnd.Next(1, 9),
            };

            var insertModel = new Model.Remove()
            {
                Fullname = fullname,
                Mail = mail,
                Message = message,
                Subject = subject,
                Username = username,
                IsActive = true,
                IsDeleted = false,
            };

            if(errorList.Count > 0)
            {
                ViewBag.ErrorList = errorList;
                return View(model);
            }

            var _data = new RemoveData();
            var check = _data.GetBy(x => x.Username == username && x.IsActive && !x.IsDeleted).FirstOrDefault();
            if(check != null)
            {
                errorList.Add("You already progress...");
                ViewBag.ErrorList = errorList;
                return View(model);
            }
            _data.Insert(insertModel);

            ViewBag.Success = "ss";
            
            return View(model);
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Team()
        {
            return View();
        }

        public ActionResult Company()
        {
            return View();
        }

        public ActionResult Privacy()
        {
            return View();
        }

    }
}

WebUI/Instagram.Analysis/Controllers/SearchController.cs
namespace Instagram.Controllers
{
    using Instagram.Analysis.Models;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;

    public class SearchController : Controller
    {
        public ActionResult Index(string param)
        {
            var model = new SearchViewModel();

            if (string.IsNullOrEmpty(param))
                return View(model);

            model = new SearchViewModel()
            {
                Param = param,
                IsEnableAds = false,
            };

            return View(model);
        }
    }
}

WebUI/Instagram.Analysis/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @if (ViewBag.Canonical != null)
    {
        <link rel="canonical" href="@ViewBag.Canonical" />
    }
    @if (ViewBag.Robots != null)
    {
        <meta name="robots" content="@ViewBag.Robots" />
    }
    @if (ViewBag.Description != null)
    {
        <meta name="description" content="@Html.Raw(ViewBag.Description)" />
    }

    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-title" content="site">
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="i-UA-Compatible" content="IE=edge,chrome=1" />
    <meta http-equiv="x-dns-prefetch-control" content="on">

</head>
<body>
    <header>
        <nav>
            <div class="siteContainer">
                <div class="siteMenuLeft">
                    <div class="logo">
                        <a href="@Url.Action("Index","Home")" title="Online instagram analyzer and viewer">
                            <img src="~/_assets/img/logo.png" alt="">
                            <p class="logoTitle">site</p>
                        </a>
                    </div>
                    <div class="search">
                        <form id="searchHeadlineForm">
                            <input type="text" name="test" id="searchInput" class="searchBar" placeholder="Search instagram User or Challenge" />
                            <button id="searchBtn"><i class="icon-search"></i></button>
                        </form>
                    </div>
                </div>
                <div class="siteMenuRight">
                    <ul>
                        <li><a href="@Url.Action("Index","Home")">Home</a></li>
                        <li><a href="@Url.Action("Index","Search")">Search</a></li>
                        <li><a href="@Url.Action("Index","Compare")">Compare</a></li>
                        <li><a href="@Url.Action("About","Page")">About Us</a></li>
                        <li><a href="@Url.Action("Privacy","Page")">Privacy Policy</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    @RenderBody()

    <footer>
        <p>site.com is first online instagram viewer and anlytics tools</p>
    </footer>

    <link rel="stylesheet" type="text/css" href="~/_assets/fonts/iconset.css" />
    <link rel="stylesheet" type="text/css" href="~/_assets/css/style.css" />


    @RenderSection("scripts", false)
</body>
</html>

WebUI/Instagram.Analysis/Views/Shared/_fileHashtagPage.cshtml
@using System.Text.RegularExpressions;
@model InstaHashtagModel
@{
    var hashmodel = Model.HasGraphql.Hashtag.HashtagMedia;
    var totalLike = 0;
    var totalComment = 0;
    var hashtags = new List<string>();
    var mentions = new List<string>();
    var locations = new List<string>();
    var mostMentions = new List<string>();
    var mostTags = new List<string>();
    int mostTagCount = 0;
    int mostMentionCount = 0;

    foreach (var item in hashmodel.Items)
    {
        totalComment = totalComment + item.Media.CommentCount.Count;
        totalLike = totalLike + item.Media.LikeCount.Count;

        if (item.Media.Caption.Edges.Count() > 0)
        {
            var capt = item.Media.Caption.Edges[0].Node.Text;
            var tags = capt.ToHashtags().OrderBy(x => Guid.NewGuid());
            var mentionsx = capt.ToMentions().OrderBy(x => Guid.NewGuid());

            foreach (var tag in tags)
            {
                if (mostTagCount == 10) { break; }
                if (mostTags.Contains(tag)) { continue; }

                mostTagCount += 1;

                var tagClear = tag.Replace("(", "")
                    .Replace(")", "")
                    .Replace("[", "")
                    .Replace("]", "");

                mostTags.Add(tagClear);
            }

            foreach (var tag in mentionsx)
            {
                if (mostMentionCount == 10) { break; }
                if (mostMentions.Contains(tag)) { continue; }

                mostMentionCount += 1;

                var tagClear = tag.Replace("(", "")
                    .Replace(")", "")
                    .Replace("[", "")
                    .Replace("]", "");

                mostMentions.Add(tagClear);
            }
        }
    }
}

<div class="instagramUserMediaList">
    @foreach (var item in Model.HasGraphql.Hashtag.HashtagMedia.Items)
    {
        var caption = "";
        var mediaCaption = "";
        if (item.Node.Caption.Edges.Count() > 0)
        {
            caption = item.Node.Caption.Edges[0].Node.Text;
            mediaCaption = item.Node.Caption.Edges[0].Node.Text;
        }
        else
        {
            mediaCaption = username + " Instagram Photos, Videos and Stroies";
        }

        <div class="siteMediaListBox siteBox-3">
            <div class="instagramMediasBox">
                <div class="instagramMedia">
                    <a href="@Url.Action("Index","Media", new { code = item.Node.ImageShort  })/" title="caption">
                        @if (item.Node.MediaType == "GraphSidecar")
                        {
                            <i class="icon-images"></i>
                        }
                        else if (item.Node.MediaType == "GraphVideo")
                        {
                            <i class="icon-play"></i>
                        }

                        <img class="zoom"
                             src="@item.Node.DisplayUrl"
                             alt="@mediaCaption"
                             title="@mediaCaption">
                    </a>
                </div>
                @if (!string.IsNullOrEmpty(caption))
                {
                    var text = caption.StripHtml().Replace("#", " #") + " ";
                    text = caption.StripHtml().Replace("@", " @") + " ";
                    var tags = caption.ToHashtags().OrderBy(x => Guid.NewGuid());
                    var xmentions = caption.ToMentions().OrderBy(x => Guid.NewGuid());
                    int counter = 0;
                    int mcounter = 0;

                    foreach (var tag in tags)
                    {
                        if (hashtags.Contains(tag)) { continue; }

                        counter += 1;

                        var tagClear = tag.Replace("(", "")
                            .Replace(")", "")
                            .Replace("[", "")
                            .Replace("]", "");

                        var url = $"/tag/{tagClear.ToLower()}/";
                        var title = tagClear.HashtagTitle();
                        var regexTag = new Regex($"#{tagClear} ", RegexOptions.IgnoreCase);

                        text = regexTag.Replace(text, $"<a href='{url}' title='{title}'>#{tagClear}</a> ", 1);

                        hashtags.Add(tagClear);

                        if (counter > 3)
                        {
                            break;
                        }
                    }

                    foreach (var ment in xmentions)
                    {
                        if (mentions.Contains(ment)) { continue; }

                        mcounter += 1;

                        var mentionClear = ment.Replace("(", "")
                            .Replace(")", "")
                            .Replace("[", "")
                            .Replace("]", "");

                        var url = $"/{mentionClear.ToLower()}/";
                        var title = mentionClear.HashtagTitle();
                        var regexTag = new Regex($"@{mentionClear} ", RegexOptions.IgnoreCase);

                        text = regexTag.Replace(text, $"<a href='{url}' title='{title}'>@{mentionClear}</a> ", 1);

                        mentions.Add(mentionClear);

                        if (mcounter > 3)
                        {
                            break;
                        }
                    }

                    <div class="instagramMediaDescription">
                        @Html.Raw(text)
                    </div>
                }
                @if (item.Node.Location != null)
                {
                    <div class="instagramMediaLocation">
                        <a href="@Url.Action("Index","Location", new { id= item.Node.Location.id })/" title="@item.Node.Location.Name places instagram videos and photos">
                            <i class="icon-location"></i><span> @item.Node.Location.Name</span>
                        </a>
                    </div>
                }
                <div class="instagramMediaStats">
                    <p><i class="icon-heart"></i> @UIHelper.ToCommaSeparetadNumber(item.Node.LikeCount.Count.ToString())</p>
                    <p><i class="icon-bubbles"></i> @UIHelper.ToCommaSeparetadNumber(item.Node.CommentCount.Count.ToString())</p>
                </div>
            </div>
        </div>
    }
</div>

WebUI/Instagram.Analysis/Views/Shared/_fileUserPage.cshtml
@using System.Text.RegularExpressions;
@model InstaAccountModel
@{
    var username = Model.Graphql.User.Username;
    var fullname = Model.Graphql.User.Fullname;
    var user = Model.Graphql.User;
    var totalLike = 0;
    var totalComment = 0;
    var hashtags = new List<string>();
    var mentions = new List<string>();
    var locations = new List<string>();
    var mostMentions = new List<string>();
    var mostTags = new List<string>();
    int mostTagCount = 0;
    int mostMentionCount = 0;

    foreach (var item in user.Media.Edges)
    {
        totalComment = totalComment + item.Node.CommentCount.Count;
        totalLike = totalLike + item.Node.LikeCount.Count;
        if (item.Node.Location != null)
        {
            var checkLoc = locations.Contains(item.Node.Location.Name);
            if (!checkLoc)
            {
                locations.Add(item.Node.Location.Name);
            }
        }

        if(item.Node.Caption.Edges.Count() > 0)
        {
            var capt = item.Node.Caption.Edges[0].Node.Text;
            var tags = capt.ToHashtags().OrderBy(x => Guid.NewGuid());
            var mentionsx = capt.ToMentions().OrderBy(x => Guid.NewGuid());
            
            foreach (var tag in tags)
            {
                if(mostTagCount == 10) { break;  }
                if (mostTags.Contains(tag)) { continue; }

                mostTagCount += 1;

                var tagClear = tag.Replace("(", "")
                    .Replace(")", "")
                    .Replace("[", "")
                    .Replace("]", "");

                mostTags.Add(tagClear);
            }
            
            foreach (var tag in mentionsx)
            {
                if(mostMentionCount == 10) { break;  }
                if (mostMentions.Contains(tag)) { continue; }

                mostMentionCount += 1;

                var tagClear = tag.Replace("(", "")
                    .Replace(")", "")
                    .Replace("[", "")
                    .Replace("]", "");

                mostMentions.Add(tagClear);
            }
        }
    }
}

<div class="main">
    <div class="siteContainer">
        <div class="instagramUserContainer">
            <div class="instagramBreadcrumb">
                <a href="/" title="Online Instagram Viewer Browse and Find Accounts and Medias">Home</a>
                <span>&gt;</span>
                <span class="username">@username</span>
            </div>
            <h1>@username's Followers/Fans in @@@username Instagram Account</h1>
            <h2>Find All Instagram Followers/Fans of @username in @@@username Instagram Account.</h2>

            <div class="instagramInfos">
                <div class="userInstagramAvatar">
                    <img src="@user.Avatar"
                         alt="@fullname's Instagram Videos, Photos and Stories in @username Instagram Account"
                         title="@fullname's Instagram Videos, Photos and Stories in @username Instagram Account"
                         width="120" height="120">
                </div>
                <p>@fullname</p>
                <p>@@@username</p>
                <p>
                    @user.Biography
                </p>
            </div>
            <div class="instagramUserAnalytics">
                <div class="instagramUserStats">
                    <i class="icon-file-picture"></i>
                    <p>Medias</p>
                    <p>@UIHelper.ToCommaSeparetadNumber(user.Media.Count.ToString())</p>
                </div>
                <div class="instagramUserStats">
                    <i class="icon-user"></i>
                    <p>Friends</p>
                    <p>@UIHelper.ToCommaSeparetadNumber(user.Followings.Count.ToString())</p>
                </div>
                <div class="instagramUserStats">
                    <i class="icon-users"></i>
                    <p>Followers</p>
                    <p>@UIHelper.ToCommaSeparetadNumber(user.Followers.Count.ToString())</p>
                </div>
                <div class="instagramUserStats">
                    <i class="icon-heart"></i>
                    <p>Total Likes</p>
                    <p>@UIHelper.ToCommaSeparetadNumber(totalLike.ToString())</p>
                </div>
                <div class="instagramUserStats">
                    <i class="icon-bubbles2"></i>
                    <p>Total Comments</p>
                    <p>@UIHelper.ToCommaSeparetadNumber(totalComment.ToString())</p>
                </div>
            </div>

            <div class="instagramStats">
                <div class="width30">
                    <h3>@username Daily Follower Changes</h3>
                    <p>This chart is daily @username follower changes on historical chart instagram statistics summary for @username</p>
                </div>
                <div class="width70">
                    <div id="followerChart"></div>
                </div>
            </div>
            <div class="instagramStats">
                <div class="width30">
                    <h3>@username Daily Friends Changes</h3>
                    <p>This chart is daily @username friends changes on historical chart instagram analytical hisyory tables for @username</p>
                </div>
                <div class="width70">
                    <div id="friendChart"></div>
                </div>
            </div>
            <div class="instagramStats">
                <div class="width30">
                    <h3>@username Daily Media/Post Changes</h3>
                    <p>This chart is daily @username media/post changes on historical chart instagram analytical hisyory tables for @username</p>
                </div>
                <div class="width70">
                    <div id="mediaChart"></div>
                </div>
            </div>

            <div class="userLastStatsBox">
                <div class="siteBox-3 userLastStats mentions">
                    <i class="icon-user"></i>
                    <p>@fullname Friends</p>
                    <ul>
                        @if (mostMentions.Count > 0)
                        {
                            foreach (var item in mostMentions)
                            {
                                <li>@item</li>
                            }
                        }
                    </ul>
                </div>
                <div class="siteBox-3 userLastStats hashtags">
                    <i class="icon-price-tags"></i>
                    <p>Last Hashtags</p>
                    <ul>
                        @if (mostTags.Count > 0)
                        {
                            foreach (var item in mostTags)
                            {
                                <li>@item</li>
                            }
                        }
                    </ul>
                </div>
                <div class="siteBox-3 userLastStats locations">
                    <i class="icon-location2"></i>
                    <p>@fullname Last Locations</p>
                    <ul>
                        @if (locations.Count > 0)
                        {
                            foreach (var item in locations)
                            {
                                <li>@item</li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </div>

        <div class="instagramUserMediaList">
            @foreach (var item in Model.Graphql.User.Media.Edges)
            {
                var caption = "";
                var mediaCaption = "";
                if (item.Node.Caption.Edges.Count() > 0)
                {
                    caption = item.Node.Caption.Edges[0].Node.Text;
                    mediaCaption = item.Node.Caption.Edges[0].Node.Text;
                }
                else
                {
                    mediaCaption = username + " Instagram Photos, Videos and Stroies";
                }

                <div class="siteMediaListBox siteBox-3">
                    <div class="instagramMediasBox">
                        <div class="instagramMedia">
                            <a href="@Url.Action("Index","Media", new { code = item.Node.ImageShort  })/" title="caption">
                                @if (item.Node.MediaType == "GraphSidecar")
                                {
                                    <i class="icon-images"></i>
                                }
                                else if (item.Node.MediaType == "GraphVideo")
                                {
                                    <i class="icon-play"></i>
                                }

                                <img class="zoom"
                                     src="@item.Node.DisplayUrl"
                                     alt="@mediaCaption"
                                     title="@mediaCaption">
                            </a>
                        </div>
                        @if (!string.IsNullOrEmpty(caption))
                        {
                            var text = caption.StripHtml().Replace("#", " #") + " ";
                            text = caption.StripHtml().Replace("@", " @") + " ";
                            var tags = caption.ToHashtags().OrderBy(x => Guid.NewGuid());
                            var xmentions = caption.ToMentions().OrderBy(x => Guid.NewGuid());
                            int counter = 0;
                            int mcounter = 0;

                            foreach (var tag in tags)
                            {
                                if (hashtags.Contains(tag)) { continue; }

                                counter += 1;

                                var tagClear = tag.Replace("(", "")
                                    .Replace(")", "")
                                    .Replace("[", "")
                                    .Replace("]", "");

                                var url = $"/tag/{tagClear.ToLower()}/";
                                var title = tagClear.HashtagTitle();
                                var regexTag = new Regex($"#{tagClear} ", RegexOptions.IgnoreCase);

                                text = regexTag.Replace(text, $"<a href='{url}' title='{title}'>#{tagClear}</a> ", 1);

                                hashtags.Add(tagClear);

                                if (counter > 3)
                                {
                                    break;
                                }
                            }

                            foreach (var ment in xmentions)
                            {
                                if (mentions.Contains(ment)) { continue; }

                                mcounter += 1;

                                var mentionClear = ment.Replace("(", "")
                                    .Replace(")", "")
                                    .Replace("[", "")
                                    .Replace("]", "");

                                var url = $"/{mentionClear.ToLower()}/";
                                var title = mentionClear.HashtagTitle();
                                var regexTag = new Regex($"@{mentionClear} ", RegexOptions.IgnoreCase);

                                text = regexTag.Replace(text, $"<a href='{url}' title='{title}'>@{mentionClear}</a> ", 1);

                                mentions.Add(mentionClear);

                                if (mcounter > 3)
                                {
                                    break;
                                }
                            }

                            <div class="instagramMediaDescription">
                                @Html.Raw(text)
                            </div>
                        }
                        @if (item.Node.Location != null)
                        {
                            <div class="instagramMediaLocation">
                                <a href="@Url.Action("Index","Location", new { id= item.Node.Location.id })/" title="@item.Node.Location.Name places instagram videos and photos">
                                    <i class="icon-location"></i><span> @item.Node.Location.Name</span>
                                </a>
                            </div>
                        }
                        <div class="instagramMediaStats">
                            <p><i class="icon-heart"></i> @UIHelper.ToCommaSeparetadNumber(item.Node.LikeCount.Count.ToString())</p>
                            <p><i class="icon-bubbles"></i> @UIHelper.ToCommaSeparetadNumber(item.Node.CommentCount.Count.ToString())</p>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>