Instagram/Models/LocationViewModel.cs
namespace Instagram.Models
{
    public class LocationViewModel
    {
        public LocationViewModel()
        {
            IsEnableAds = true;
        }

        public bool IsEnableAds { get; set; }
        public string Location { get; set; }
    }
}

Instagram/Controllers/LocationController.cs
namespace Instagram.Controllers
{
    using Instagram.Helpers;
    using Instagram.Models;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;

    public class LocationController : Controller
    {
        // GET: Location
        public ActionResult Index(string id)
        {
            //return Redirect("http://hotsta.net/loc/"+id+"/");

            var ban = CacheHelper.BanLocations.Where(x => x.Value == id).FirstOrDefault();
            if (ban != null)
                return RedirectToAction("Index", "Home", new { q = "location-is-block" });

            if (!Request.Path.EndsWith("/"))
                return RedirectPermanent(Request.Url.ToString() + "/");

            if (string.IsNullOrEmpty(id))
                return RedirectToAction("Index", "Home", new { q = "location-empty" });

            var model = new LocationViewModel()
            {
                Location = id,
                IsEnableAds = false,
            };

            return View(model);
        }

        public ActionResult Geo(string id)
        {
            return Redirect("http://hotsta.net/loc/" + id + "/");
        }

        [HttpGet]
        [ValidateInput(false)]
        public ActionResult Ban(string id)
        {
            if (string.IsNullOrEmpty(id))
                return RedirectToAction("Index", "Home", new { q = "id-empty" });

            var model = new Model.BanLocation()
            {
                Description = "ban",
                Value = id,
            };

            CacheHelper.BanLocations.Add(model);

            var result = new Data.BanLocationData().Insert(model);
            if (result.IsSucceed)
                return RedirectToAction("Index", "Home", new { q = "location_banned" });
            else
                return RedirectToAction("Index", "Home", new { q = "location_error_banned" });
        }
    }
}

Instagram/Views/Location/Index.cshtml
@model LocationViewModel
@{
    ViewBag.Title = "Instagram location medias";
    ViewBag.Description = "Instagram location photos and videos of sitename Location top and recent all medias on sitename";
    ViewBag.Robots = "index,follow";
    ViewBag.Canonical = Url.Action("Index", "Location", new { id = Model.Location });
}

<div class="site-content--extra-large site-grid">
    <div class="site-grid-row">
        <div class="site-grid-col site-grid-col--12 ">
            <div class="centered">
                <p class="site-box-title no-spacing">
                </p>
            </div>
            <div class="centered">
                <h1>Loading...</h1>
                <h2 class="site-jumbotron-subtitle"></h2>
            </div>
        </div>
    </div>
</div>

<div class="site-content--extra-large site-grid">
    <div class="site-grid-row grid gallery" data-colcade="columns: .grid-col, items: .grid-item" id="fth">
        <div class="grid-col grid-col--1"></div>
        <div class="grid-col grid-col--2"></div>
        <div class="grid-col grid-col--3"></div>
    </div>

</div>


<button class="site-btn site-btn--light search-btn" onclick="openSearch()"><i class="ti-search"></i></button>
<input type="hidden" id="lastId" value="299559812707734679" />


<div id="myOverlay" class="overlay">
    <div class="overlay-content">
        <div class="site-form">
            <div class="site-form-field">
                <input type="text" name="q" id="q" placeholder="Type something to search..." class="site-input site--width-50" value="">
                <button class="site-btn site-btn--blue btn-search" id="fire"><i class="ti-search"></i></button>
                <button class="closebtn site-btn site-btn--red" onclick="closeSearch()" title="Close Overlay"><i class="ti-close"></i></button>
            </div>
        </div>
    </div>
</div>
<div class="loader"></div>

@section scripts{
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
    <script src="~/assets/js/instagram.js"></script>

    <script>

        instagram.location("@Model.Location","funny");

        document.querySelector("#q").onkeypress = function (e) {
            if (e.keyCode == 13) {
                value = clearForSearch(this.value.toLowerCase());

                window.location.assign("/search/" + value + "/");
                return false;
            }
        };
        function clearForSearch(value) {
            value = value.toLowerCase();
            value = value.replace(/ /g, ' ');
            value = value.replace('#', '');
            value = value.replace('<', '');
            value = value.replace('>', '');
            value = value.replace('%', '');
            value = value.replace('&', '');
            value = value.replace('.', '');
            value = value.replace('*', '');
            value = value.replace('/', '');
            value = value.replace('~', '');
            value = value.replace(';', '');
            value = value.replace('@@', '');
            return value;
        }

        document.querySelector("#fire").onclick = function () {
            value = clearForSearch(document.querySelector("#q").value);
            if (value == '')
                ;
            else
                window.location.assign("/search/" + value + "/");

            return false;
        }

        function openSearch() {
            document.getElementById("myOverlay").style.display = "block";
        }

        function closeSearch() {
            document.getElementById("myOverlay").style.display = "none";
        }



    </script>


}