Instagram/Controllers/ListController.cs
namespace Instagram.Controllers
{
    using Instagram.Data;
    using Instagram.Models;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;

    public class ListController : Controller
    {
        PopularAccountData _popularAccountData;
        CategoryData _categoryData;
        HashtagData _hashtagData;

        public ListController()
        {
            _popularAccountData = new PopularAccountData();
            _categoryData = new CategoryData();
            _hashtagData = new HashtagData();
        }

        public ActionResult Index(int page = 1)
        {
            //return Redirect("http://hotsta.net/popular-accounts/");

            if (!Request.Path.EndsWith("/"))
                return RedirectPermanent(Request.Url.ToString() + "/");

            var populars = _popularAccountData.GetByPage(page, 100, "Followers", true);

            var model = new ListViewModel()
            {
                PopularAccounts = populars,
                Page = page,
            };

            return View(model);
        }

        public ActionResult Category()
        {
            //return Redirect("http://hotsta.net/popular-categories/");

            if (!Request.Path.EndsWith("/"))
                return RedirectPermanent(Request.Url.ToString() + "/");

            var categories = _categoryData.GetAll();

            var model = new ListCategoryViewModel()
            {
                Categories = categories
            };

            return View(model);
        }

        public ActionResult Hashtag()
        {
            //return Redirect("http://hotsta.net/popular-hashtags/");

            if (!Request.Path.EndsWith("/"))
                return RedirectPermanent(Request.Url.ToString() + "/");

            var hashtags = _hashtagData.GetAll();

            var model = new ListHashtagViewModel()
            {
                Hashtags = hashtags
            };

            return View(model);
        }

        public ActionResult Detail(string slug, int page = 1)
        {
            //return Redirect("http://hotsta.net/categories/");

            if (!Request.Path.EndsWith("/"))
                return RedirectPermanent(Request.Url.ToString() + "/");

            if (string.IsNullOrEmpty(slug))
                return RedirectToAction("Index", "Home", new { q = "slug-is-empty" });

            var cat = _categoryData.GetBy(x => x.Slug == slug).FirstOrDefault();
            if (cat == null)
                return RedirectToAction("Index", "Home", new { q = "not-found-category", e = slug });
            
            var populars = _popularAccountData.GetByPage(x=>x.CategoryId == cat.Id, page, 100, "Followers", true);

            var model = new DetailViewModel()
            {
                PopularAccounts = populars,
                Page = page,
                Category= cat,
            };

            return View(model);
        }
    }
}

Instagram/Controllers/PageController.cs
namespace Instagram.Controllers
{
    using Instagram.Data;
    using Instagram.Models;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;

    public class PageController : Controller
    {
        public ActionResult Index(string username)
        {
            //return Redirect("http://hotsta.net/report-a-problem/");

            if (!Request.Path.EndsWith("/"))
                return RedirectPermanent(Request.Url.ToString() + "/");

            if (string.IsNullOrEmpty(username))
                username = "";

            Random rnd = new Random();
            
            var model = new ReportModel()
            {
                Fullname = "",
                MailAddress = "",
                Message = "",
                Username = username,
                Subject = "",
                Captha1 = rnd.Next(1,9),
                Captha2 = rnd.Next(1,9),
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult Index(string fullname, string mail, string message, string username, string subject, int capt1, int capt2, int captcha)
        {
            int capResult = capt1 + capt2;
            var errorList = new List<string>();
            if (captcha <= 0)
                errorList.Add("Captcha empty");
            if (captcha != capResult)
                errorList.Add("Captcha Error");
            if(string.IsNullOrEmpty(fullname))
                errorList.Add("Fullname empty");
            if (string.IsNullOrEmpty(mail))
                errorList.Add("EMail empty");
            if (string.IsNullOrEmpty(message))
                errorList.Add("Message empty");
            if (string.IsNullOrEmpty(username))
                errorList.Add("Username empty");
            if (string.IsNullOrEmpty(subject))
                errorList.Add("Subject empty");

            Random rnd = new Random();

            var model = new ReportModel()
            {
                Fullname = fullname,
                MailAddress = mail,
                Message = message,
                Subject = subject,
                Username = username,
                Captha1 = rnd.Next(1, 9),
                Captha2 = rnd.Next(1, 9),
            };

            var insertModel = new Model.Remove()
            {
                Fullname = fullname,
                Mail = mail,
                Message = message,
                Subject = subject,
                Username = username,
                IsActive = true,
                IsDeleted = false,
            };

            if(errorList.Count > 0)
            {
                ViewBag.ErrorList = errorList;
                return View(model);
            }

            var _data = new RemoveData();
            var check = _data.GetBy(x => x.Username == username && x.IsActive && !x.IsDeleted).FirstOrDefault();
            if(check != null)
            {
                errorList.Add("You already progress...");
                ViewBag.ErrorList = errorList;
                return View(model);
            }
            _data.Insert(insertModel);

            ViewBag.Success = "ss";
            
            return View(model);
        }

        public ActionResult About()
        {
            //return Redirect("http://hotsta.net/about/");

            if (!Request.Path.EndsWith("/"))
                return RedirectPermanent(Request.Url.ToString() + "/");

            return View();
        }

        public ActionResult Team()
        {
            //return Redirect("http://hotsta.net/team/");

            if (!Request.Path.EndsWith("/"))
                return RedirectPermanent(Request.Url.ToString() + "/");

            return View();
        }

        public ActionResult Company()
        {
            //return Redirect("http://hotsta.net/company/");

            if (!Request.Path.EndsWith("/"))
                return RedirectPermanent(Request.Url.ToString() + "/");

            return View();
        }

        public ActionResult Privacy()
        {
            //return Redirect("http://hotsta.net/privacy-policy/"); 

            if (!Request.Path.EndsWith("/"))
                return RedirectPermanent(Request.Url.ToString() + "/");

            return View();
        }

    }
}

Instagram/Controllers/SearchController.cs
namespace Instagram.Controllers
{
    using Instagram.Models;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;

    public class SearchController : Controller
    {
        public ActionResult Index(string param)
        {
            /*if (string.IsNullOrEmpty(param))
                return Redirect("http://hotsta.net/search/");
            else
                return Redirect("http://hotsta.net/search/" + param + "/");*/

            if (!Request.Path.EndsWith("/"))
                return RedirectPermanent(Request.Url.ToString() + "/");

            var model = new SearchViewModel();
            if (string.IsNullOrEmpty(param))
                return View(model);

            model = new SearchViewModel()
            {
                Param = param,
                IsEnableAds = false,
            };

            return View(model);
        }
    }
}

Instagram/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-extendedible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>
    @if (ViewBag.Description != null)
    {
        <meta name="description" content="@ViewBag.Description">
    }

    @if (ViewBag.Robots != null)
    {
        <meta name="robots" content="@ViewBag.Robots">
    }

    @if (ViewBag.Canonical != null)
    {
        <link rel="canonical" href="@ViewBag.Canonical" />
    }
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
    <meta property="og:title" content="@ViewBag.Title" />
    <meta property="og:description" content="@ViewBag.Description">
    <meta property="og:image" />
    <meta property="og:image:width" content="450">
    <meta property="og:image:height" content="298">
    <meta name="twitter:site" content="@CacheHelper.Setting.Sitename">
    <meta name="twitter:title" content="@ViewBag.Title">
    <meta name="twitter:description" content="@ViewBag.Description">
    <meta name="twitter:domain" content="@CacheHelper.Setting.Siteadres">
    <meta name="twitter:image">

    
    
</head>
<body>
    <div class="site-navbar sd-header site-navbar--extra-large " id="main">
        <a class="site-navbar-title" title="The Most Powerful and Responsive Social Media Analytics Platform Available • @CacheHelper.Setting.Sitename" href="/">@CacheHelper.Setting.Sitename</a>
        <a class="site-navbar-subtitle  site--color-white" href="/" title="The Most Powerful and Responsive Social Media Analytics Platform Available • @CacheHelper.Setting.Sitename">Social Media Analytics</a>
        <label for="drop" class="toggle site-navbar-item site--float-right">&#9776;</label>
        <div class="site--float-right">
            <nav>
                <input type="checkbox" id="drop">
                <ul class="menu">
                    <li>
                        <a href="/" title="The Most Powerful and Responsive Social Media Analytics Platform Available • @CacheHelper.Setting.Sitename" class="site-navbar-item">Home</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","Search")/" title="Search instagram account or hashtags" class="site-navbar-item">Search</a>
                    </li>
                    <li>
                        <label for="drop-1" class="toggle site-navbar-item">Top Lists <span class="ti-angle-down"></span></label>
                        <a href="#" class="site-navbar-item">Top Lists <span class="ti-angle-down"></span></a>
                        <input type="checkbox" id="drop-1">
                        <ul class="nav-box">
                            <li><a href="@Url.Action("Index","List")/" title="Intagram popular accounts"><span class="ti-star"></span>&nbsp; Popular Accounts</a></li>
                            <li><a href="@Url.Action("Hashtag","List")/" title="Intagram popular hashtags">#&nbsp; Top Hashtags</a></li>
                            <li><a href="@Url.Action("Category","List")/" title="Intagram popular hashtags"><span class="ti-layers"></span>&nbsp; Top Categories</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </div>
    </div>

    @RenderBody()


    <div class="site-box-flat site--bg-dark centered">
        <div class="sd-group-header-title site--color-white">
            Please Don't Hesitate To Connect With Us
        </div>
    </div>
    <div class="site-footer site-footer--dark site-content--large " align="center">
        <div class="site-grid-row">
            <div class="site-grid-col site-grid-col--3 site-grid-col--xs-6">
                <div class="site-menu">
                    <div class="site-menu-group">  <h3>About Us</h3></div>
                    <a href="@Url.Action("Company","Page")/" class="site-menu-item  site--color-white">Company</a>
                    <a href="@Url.Action("Team","Page")/" class="site-menu-item site--color-white">Team</a>
                </div>
            </div>
            <div class="site-grid-col site-grid-col--3 site-grid-col--xs-6">
                <div class="site-menu">
                    <div class="site-menu-group">  <h3>Contact Us</h3></div>
                    <a class="site-menu-item site--color-white">Contact Form</a>
                    <a class="site-menu-item  site--color-white">Join Newsletter</a>
                </div>
            </div>
            <div class="site-grid-col site-grid-col--3 site-grid-col--xs-6">
                <div class="site-menu">
                    <div class="site-menu-group">  <h3>Legal</h3></div>
                    <a class="site-menu-item  site--color-white" href="@Url.Action("Privacy","Page")/">Privacy Policy</a>
                    <a class="site-menu-item site--color-white" href="@Url.Action("Index","Page")/">Report a Problem</a>
                </div>
            </div>
            <div class="site-grid-col site-grid-col--3 site-grid-col--xs-6">
                <div class="site-menu">
                    <div class="site-menu-group">  <h3 class="site-h3">Follow Us</h3></div>
                    <a class="site-menu-item  site--color-white site--float-left" href="#"> <span class="ti-instagram icon-4x "></span></a>
                    <a class="site-menu-item  site--color-white site--float-left" href="#"> <span class="ti-twitter icon-4x"></span></a>
                    <a class="site-menu-item  site--color-white site--float-left" href="#"> <span class="ti-facebook icon-4x"></span></a>
                    <a class="site-menu-item  site--color-white site--float-left" href="#"> <span class="ti-pinterest icon-4x"></span></a>
                </div>
            </div>
        </div>
        <div class="footer-fix">
            <div class="site-grid-col site-grid-col--12">
                <small>2018 @CacheHelper.Setting.Sitename - All rights reserved. All copyrights belong to their respective owners.</small>
            </div>
        </div>
    </div>

    <span class="site-btn site-btn--primary totop" onclick="window.scrollTo(0, 0);"><strong><i class="ti-arrow-up site--color-white"></i></strong></span>


    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700&amp;subset=cyrillic,cyrillic-ext,latin-ext,vietnamese" rel="stylesheet" lazyload />
    <link href="~/assets/css/style.css" rel="stylesheet" />
    @Html.Raw(CacheHelper.Setting.Analytics)


    @RenderSection("scripts", false)
</body>
</html>