Instagram/Models/HashtagViewModel.cs
namespace Instagram.Models
{
    public class HashtagViewModel
    {
        public HashtagViewModel()
        {
            IsEnableAds = true;
        }

        public bool IsEnableAds { get; set; }
        public string Hashtag { get; set; }
    }
}

Instagram/Controllers/HashtagController.cs
namespace Instagram.Controllers
{
    using Instagram.Helpers;
    using Instagram.Models;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;

    public class HashtagController : Controller
    {
        public ActionResult Index(string hashtag)
        {
            var ban = CacheHelper.BanHashtags.Where(x => x.Value == hashtag).FirstOrDefault();
            if (ban != null)
                return RedirectToAction("Index", "Home", new { q = "hashtag-is-block" });

            if (!Request.Path.EndsWith("/"))
                return RedirectPermanent(Request.Url.ToString() + "/");


            if (string.IsNullOrEmpty(hashtag))
                return RedirectToAction("Index", "Home", new { q = "hashtag-empty" });

            var model = new HashtagViewModel()
            {
                Hashtag = hashtag,
                IsEnableAds = false,
            };

            return View(model);
        }

        [HttpGet]
        [ValidateInput(false)]
        public ActionResult Ban(string hashtag)
        {
            if (string.IsNullOrEmpty(hashtag))
                return RedirectToAction("Index", "Home", new { q = "hashtag-empty" });

            var model = new Model.BanHashtag()
            {
                Description = "ban",
                Value = hashtag,
            };

            CacheHelper.BanHashtags.Add(model);

            var result = new Data.BanHashtagData().Insert(model);
            if (result.IsSucceed)
                return RedirectToAction("Index", "Home", new { q = "hashtag_banned" });
            else
                return RedirectToAction("Index", "Home", new { q = "error_hashtag_banned" });
        }
    }
}

Instagram/Views/Hashtag/Index.cshtml
@model HashtagViewModel
@{
    ViewBag.Title = "Browse Instagram " + Model.Hashtag + " ideas";
    ViewBag.Description = "Browse Instagram " + Model.Hashtag + " ideas, Browse " + Model.Hashtag + " photos, videos and " + Model.Hashtag + " medias";
    ViewBag.Canonical = Url.Action("Index", "Hashtag", new { hashtag = Model.Hashtag });
    ViewBag.Robots = "index,follow";
}

<div class="centered" id="stickybar">

</div>
<div class="site-content--extra-large site-grid">
    <div class="site-grid-row">
        <div class="site-grid-col site-grid-col--12 ">
            <div class="centered">
                <p class="site-box-title no-spacing">
                    Loading...
                </p>
            </div>
            <div class="centered">
                <h1>Loading...</h1>
                <h2 class="site-jumbotron-subtitle">Loading...</h2>
            </div>
        </div>
    </div>
</div>

<div class="site-content--extra-large site-grid">
    <div class="site-grid-row grid gallery" data-colcade="columns: .grid-col, items: .grid-item" id="fth">
        <div class="grid-col grid-col--1"></div>
        <div class="grid-col grid-col--2"></div>
        <div class="grid-col grid-col--3"></div>
    </div>
</div>

<button class="site-btn site-btn--light search-btn" onclick="openSearch()"><i class="ti-search"></i></button>

<div id="myOverlay" class="overlay">
    <div class="overlay-content">
        <div class="site-form">
            <div class="site-form-field">
                <input type="text" name="q" id="q" placeholder="Type something to search..." class="site-input site--width-50" value="">
                <button class="site-btn site-btn--blue btn-search" id="fire"><i class="ti-search"></i></button>
                <button class="closebtn site-btn site-btn--red" onclick="closeSearch()" title="Close Overlay"><i class="ti-close"></i></button>
            </div>
        </div>
    </div>
</div>

<div class="loader"></div>
@section scripts{
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
    <script src="~/assets/js/instagram.js"></script>

    <script>

        instagram.hashtag("@Model.Hashtag");

        window.onscroll = function () { myFunction() };

        var stickybar = document.getElementById("stickybar");
        var sticky = stickybar.offsetTop;

        function myFunction() {
            if (window.pageYOffset >= sticky) {
                stickybar.classList.add("sticky")
            }
            else {
                stickybar.classList.remove("sticky");
            }
        }

        document.querySelector("#q").onkeypress = function (e) {
            if (e.keyCode == 13) {
                value = clearForSearch(this.value.toLowerCase());

                window.location.assign("/search/" + value + "/");
                return false;
            }
        };
        function clearForSearch(value) {
            value = value.toLowerCase();
            value = value.replace(/ /g, ' ');
            value = value.replace('#', '');
            value = value.replace('<', '');
            value = value.replace('>', '');
            value = value.replace('%', '');
            value = value.replace('&', '');
            value = value.replace('.', '');
            value = value.replace('*', '');
            value = value.replace('/', '');
            value = value.replace('~', '');
            value = value.replace(';', '');
            value = value.replace('@@', '');
            return value;
        }

        document.querySelector("#fire").onclick = function () {
            value = clearForSearch(document.querySelector("#q").value);
            if (value == '')
                ;
            else
                window.location.assign("/search/" + value + "/");

            return false;
        }

        function openSearch() {
            document.getElementById("myOverlay").style.display = "block";
        }

        function closeSearch() {
            document.getElementById("myOverlay").style.display = "none";
        }
    </script>
}